#!/bin/bash

sudo apt install curl
SYSTEM="entertainment"
source ./utils/env
# nix install
source ./utils/nix $SYSTEM
# vim configuration
source ./utils/vim
# emulation environment configuration
source ./utils/emu
