#!/bin/bash

repos=$(wget -qO - https://github.com/eikrt\?tab\=repositories |grep codeRepository |awk '{print $2}' |sed -e "s/href=\"\/eikrt\///" -e s/"\""//)

index=1

while IFS= read -r line; do
    echo $index $line
    ((index++))
done <<< "$repos"

echo enter the row number to git clone
read chosen_row
repo=$(awk -v var=$chosen_row 'FNR == var {print}' <<< "$repos")
git clone "ssh://git@github.com/eikrt/$repo"
